sudo: false 
language: cpp

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

# The different configurations we want to test.
matrix:
  # Build with different GHC versions and stable package sets
  include:
  - env: RESOLVER=lts-14
    compiler: "LTS14"
  - env: RESOLVER=lts-15
    compiler: "LTS15"
  - env: RESOLVER=nightly
    compiler: "nightly"

  - env: RESOLVER=lts-14
    compiler: "LTS14"
    os: osx
  - env: RESOLVER=lts-15
    compiler: "LTS15"
    os: osx
  - env: RESOLVER=nightly
    compiler: "nightly"
    os: osx

  - env: RESOLVER=lts-14
    compiler: "LTS14"
    os: windows
  - env: RESOLVER=lts-15
    compiler: "LTS15"
    os: windows
  - env: RESOLVER=nightly
    compiler: "nightly"
    os: windows

before_install:
- if [[ $TRAVIS_OS_NAME == 'windows' ]]; then choco install haskell-stack; else curl -sSL https://get.haskellstack.org/ | sh; fi

install:
- travis_wait 180 stack build --no-terminal --haddock --no-haddock-deps --resolver $RESOLVER

script:
- stack test web3:unit --no-terminal --resolver $RESOLVER
